apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler

metadata:
  name: node
  namespace: default

spec:
  maxReplicas: 9
  minReplicas: 2
  # Target your node app deployment so the hpa knows which
  # deployment to scale up on demand, scales down when no longer needed
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node
  targetCPUUtilizationPercentage: 50