apiVersion: v1
kind: Service
metadata:
  name: node-deployment
  namespace: default
spec:
  ports:
  - nodePort: 30442
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: node-deployment
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: localhost